language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
bundler_args: --without development
before_install:
  - gem update bundler
before_script:
  - "mysql -e 'create database one_click_test;' > /dev/null"
  - "bundle exec rake oco:generate_config db:migrate db:test:prepare"
  - "RAILS_ENV=test bundle exec rake db:seed"
  - "bundle exec rake oco:install_wkhtmltopdf"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export COVERALLS_MERGE_TIMEOUT=3600"
script: bundle exec rake test_with_coveralls
branches:
  only:
    - master
    - v1.3.x
notifications:
  recipients:
    - alerts@oneclickorgs.com
  irc: "irc.freenode.net#oneclickorgs"
