language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
bundler_args: --without development
before_script:
  - "mysql -e 'create database one_click_test;' > /dev/null"
  - "bundle exec rake oco:generate_config db:migrate"
  - "bundle exec rake oco:install_wkhtmltopdf"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rake test_with_coveralls
branches:
  only:
    - master
    - coop
    - v1.x
notifications:
  recipients:
    - alerts@oneclickorgs.com
  irc: "irc.freenode.net#oneclickorgs"
