language: ruby
rvm:
  - 1.9.2
  - 1.8.7
bundler_args: --without development
before_script:
  - "mysql -e 'create database one_click_test;' > /dev/null"
  - "bundle exec rake oco:generate_config db:migrate"
  - "bundle exec rake oco:install_wkhtmltopdf"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec cucumber --require features features/association_founding/accepting_a_founding_member_invitation.feature
branches:
  only:
    - master
    - v1.x
notifications:
  recipients:
    - alerts@oneclickorgs.com
  irc: "irc.freenode.net#oneclickorgs"
